apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-lab-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/s-jaiganesh/gitops-deploy-lab
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
